version: 2

jobs:
  golang-1.11-pipeline:
    working_directory: /home/circleci/app
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          keys:
            - golang-1.11-{{ checksum "go.sum" }}
      - run: go get ./...
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b /go/bin v1.17.1
      - save_cache:
          key: golang-1.11-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: run static analysis & tests
          command: make ci

  golang-1.12-pipeline:
    working_directory: /home/circleci/app
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          keys:
            - golang-1.12-{{ checksum "go.sum" }}
      - run: go get ./...
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b /go/bin v1.17.1
      - save_cache:
          key: golang-1.12-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: run static analysis & tests
          command: make ci

  golang-1.13-pipeline:
    working_directory: /home/circleci/app
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          keys:
            - golang-1.13-{{ checksum "go.sum" }}
      - run: go get ./...
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b /go/bin v1.17.1
      - save_cache:
          key: golang-1.13-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: run static analysis & tests
          command: make ci

workflows:
  version: 2
  commit:
    jobs:
      - golang-1.11-pipeline
      - golang-1.12-pipeline
      - golang-1.13-pipeline
