---
name: Golang
'on': push
jobs:
  golang:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            shasum: shasum -a 512
          - os: ubuntu-latest
            shasum: sha512sum
          - os: windows-latest
            shasum: sha512sum
    steps:
      - uses: actions/checkout@v3
      - uses: 030/golang-action@v0.1.0
        with:
          app: dive
          githubAction: ${{ secrets.GITHUB_TOKEN }}
