name: 'snapshot'
on: [push, pull_request]
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.x'
    - uses: actions/checkout@v1
    - name: install deps
      run: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sudo sh -s -- -b /usr/local/bin/ latest
        curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sudo sh -s -- -b /usr/local/bin/ latest
        sudo apt-get update
        sudo apt-get install -y libdevmapper-dev libgpgme11-dev
    - run: go get ./...
    - run: golangci-lint run -v
    - run: goreleaser --snapshot --skip-publish --rm-dist
    - run: docker images
    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist
